substitutions:
  name: "environment-sensor-lite"
  friendly_name: "Environment Sensor Lite"
  log_level: "DEBUG"
  illuminance_update_interval: "60s"

esphome:
  name: ${name}
  comment: Environment Sensors Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project:
    name: VertexAutomation.Environment Sensors Lite
    version: "1.0.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: ESP-IDF

logger:
  level: ${log_level}

api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

wifi:

improv_serial:

i2c:
  sda: 8
  scl: 9
  scan: true

sensor:
  - platform: veml7700
    address: 0x10
    update_interval: 60s
    ambient_light:
      name: "Ambient Light"
      disabled_by_default: false
      force_update: false
      unit_of_measurement: "lx"
      icon: mdi:brightness-7
      accuracy_decimals: 0
      device_class: illuminance
      state_class: measurement
    ambient_light_counts:
      name: "Ambient Light Counts"
      disabled_by_default: false
      force_update: false
      unit_of_measurement: "#"
      icon: mdi:brightness-6
      accuracy_decimals: 0
      device_class: illuminance
      state_class: measurement
    actual_integration_time:
      name: "Actual Integration Time"
      disabled_by_default: false
      force_update: false
      unit_of_measurement: "ms"
      icon: mdi:timer-outline
      accuracy_decimals: 0
      state_class: measurement
    actual_gain:
      name: "Actual Gain"
      disabled_by_default: false
      force_update: false
      icon: mdi:multiplication
      accuracy_decimals: 3
      state_class: measurement
    integration_time: 400ms
    auto_mode: true
    gain: "1/8X"
    lux_compensation: true
    glass_attenuation_factor: 1.0

  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: rssi_sensor
    update_interval: 60s
    disabled_by_default: false
    force_update: false
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    device_class: signal_strength
    state_class: measurement
    entity_category: diagnostic

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    disabled_by_default: false
    entity_category: config
    device_class: restart

